# Generated by Django 6.1.1 on 2026-09-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=1000)),
                ('game', models.CharField(choices=[('valorant', 'Valorant'), ('bgmi', 'BGMI'), ('free-fire', 'Free Fire')], max_length=20)),
                ('leader_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
